### ISSUE TITLE
Intermittent failure getting module info

### ISSUE THREAD

**Issue by chrismcg** [sonerdy/double#17]
Firstly thanks for making this library! I was thinking of implementing something similar and very glad I came across it.

I'm seeing intermittent failures like this:

```
  1) test something (MyApp.SomeTest)
     test/my_app/some_test.exs:12
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.get_module_info(MyApp.SomeModule, :functions)
```

From playing around in iex it appears that `:erlang.get_module_info` will fail with the argument error unless `MyApp.SomeModule.module_info` is called first. Once I've called `module_info` on the module the `:erlang` call works.

I've worked round this for now by calling `.module_info` in the `setup`. It looks like the information you use is in the `exports` part of what `module_info` returns and this works for both Erlang and Elixir modules so maybe that would work instead and solve the problem.

Thanks again for the very handy library!

**Comment by brandonjoyce** [comment]
Very happy to hear you're finding this library useful!  Also really happy you reported this with a suggested fix because I've been having the same problem, but I was working around it by simply requiring the modules being stubbed in each test.  Your .module_info suggestion works just as well, and it's an easy change.  I can't say exactly why this works, but the tests are passing so 👍
